name: Deploy Bot to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Bot to Google Cloud VM
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: josephfortman/communitydiscordbot
          tags: |
            type=raw,value={{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{secrets.GCE_SA_KEY}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Prune GCloud Images
        run: |
          gcloud compute ssh ${{secrets.GCE_INSTANCE_NAME}} --zone us-east1-b --command 'docker system prune -f -a'

      - name: Deploy to Google Compute Engine
        run: |
          gcloud compute instances update-container --container-image=josephfortman/communitydiscordbot:${{sha}} --container-env='DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}' --zone us-east1-b ${{secrets.GCE_INSTANCE_NAME}}
